version: '3.8'

services:
  web1:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://admin:password@db:5432/jobsdb
    depends_on:
      - db

  web2:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://admin:password@db:5432/jobsdb
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jobsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: