"""JobSkill

Revision ID: ef616eb2c7d4
Revises: de9fa05cc2f1
Create Date: 2025-04-28 08:08:13.058317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef616eb2c7d4'
down_revision = 'de9fa05cc2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_skills')
    # ### end Alembic commands ###
